### ISSUE TITLE
ILP32 build failure

### ISSUE THREAD

**Issue by jengelh** [c-util/c-sundry#4]
i586 build of c-sundry v1 fails:
```
[   36s] ../src/test-macro.c: In function ‘test_misc’:
[   36s] ../src/test-macro.c:282:17: error: static assertion failed: ""
[   36s]                  static_assert(C_DECIMAL_MAX(unsigned long) == 21, "");
[   36s]                  ^
```

**Comment by dvdhrm** [comment]
Oops, that clearly does not work on 32bit platforms. Fixed in https://github.com/c-util/c-sundry/commit/bdf6e5fcfd0c8bc956545ebf2855de36cab855b5.

Thanks!

(I'm working on CI for 32bit, big-endian, etc., right now, so hopefully this will all be fixed in a few weeks.)
